# when running on the actual car change /IS_ONLINE/ to True, otherwise False

from enum import Enum

global IS_ONLINE

global DISPLAY_LANE_DETECTION_DEBUG
global USE_YT_LANE_DETECTION_PARAMETERS
global SEND_IMAGE

global DO_SIGN_DETECTION
global DO_SEMAPHORE_DETECTION

global MEASURE_SIGN_DETECTION_TIME
global MEASURE_LANE_DETECTION_TIME
global MEASURE_LANE_NAVIGATION_TIME

global LANE_DEBUG_PRINT
global PID_DEBUG_PRINT

global DO_PEDESTRIAN

DO_PEDESTRIAN = False

LANE_DEBUG_PRINT = True
PID_DEBUG_PRINT = False

IS_ONLINE = True

SEND_DEBUG_IMAGE = True
DISPLAY_LANE_DETECTION_DEBUG = False

DO_SIGN_DETECTION = True
DO_SEMAPHORE_DETECTION = False

MEASURE_SIGN_DETECTION_TIME = True
MEASURE_LANE_DETECTION_TIME = True
MEASURE_LANE_NAVIGATION_TIME = True
MEASURE_PEDESTRIAN_DETECTION_TIME = True

USE_YT_LANE_DETECTION_PARAMETERS = True 

class State(Enum):
    LANE_FOLLOWING = 0
    INTERSECTION = 1
    WAITING = 2
    SLOW_DOWN = 3
    GO_TO_STOP_LINE = 4
    PARKING = 5
